version: '3.7'

services:
  app:
    image: knoriy/dataset_collection_tool
    build:
      context: .
    volumes:
      - ./django_dataset_collection_tool:/app # Copy these files to teh dockerfile
      - static_data:/vol/web
    env_file:
      - ./ENVIROMENT_VARIABLES
    environment:
      - DEBUG=1

  proxy:
    image: knoriy/test_proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"

    depends_on:
      - app

volumes:
  static_data: