version: '3.7'

services:
  app:
    image: knoriy/dataset_collection_tool
    build:
      context: .
    volumes:
      - ./django_dataset_collection_tool:/app # Copy these files to the dockerfile
    env_file:
      - ./env_variables.conf
    environment:
      - DEBUG=0
    restart: always

  proxy:
    image: knoriy/nginx_reverse_proxy
    build:
      context: ./proxy
    volumes:
      - ./django_dataset_collection_tool/static:/vol/static
      - ./django_dataset_collection_tool/media/:/vol/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always