version: '3.7'

services:
  app:
    image: knoriy/dataset_collection_tool
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./django_dataset_collection_tool:/app
      - ./proxy:/proxy
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      # - ./ENVIROMENT_VARIABLES
      - ./env_variables.conf

    # environment:
      # - DEBUG=1